export const ACTIONS_USER = {
  LOGIN_STATUS: "LOGIN_STATUS",
  USER_INFO: "USER_INFO",
  ACCESS_TOKEN: "ACCESS_TOKEN",
  USER_LIKE: "USER_LIKE",
  USER_LIKE_PHOTO: "USER_LIKE_PHOTO",
};
export const ACTIONS_MODAL = {
  MODAL_STATUS: "MODAL_STATUS",
  MODAL_NAME: "MODAL_NAME",
  MODAL_MESSAGE: "MODAL_MESSAGE",
};
export const ACTIONS_PLACE = {
  PLACE_LIST: "PLACE_LIST",
  NEXT_PLACE_LIST: "NEXT_PLACE_LIST",
  MY_PLACE_LIST: "MY_PLACE_LIST",
  PLACE_DATA: "PLACE_DATA",
  PLAN_LIST: "PLAN_LIST",
};
export const ACTIONS_HEADER = {
  HEADER_STATUS: "HEADER_STATUS",
};
