export const options = [
  "서울",
  "인천",
  "대전",
  "대구",
  "울산",
  "부산",
  "광주",
  "경기",
  "강원도",
  "충청북도",
  "충청남도",
  "경상북도",
  "경상남도",
  "전라북도",
  "전라남도",
  "제주도",
];

export const theme = [
  { id: 1, title: "가족" },
  { id: 2, title: "계곡" },
  { id: 3, title: "데이트" },
  { id: 4, title: "레저" },
  { id: 5, title: "바다" },
  { id: 6, title: "산" },
  { id: 7, title: "야경" },
  { id: 8, title: "역사&문화" },
  { id: 9, title: "캠핑" },
  { id: 10, title: "휴식&힐링" },
];
