import { modalActions } from "./modal";
import {
  userActions,
  signInReq,
  signUpReq,
  nonUserReq,
  googleReq,
  kakaoReq,
  userInfoPostReq,
  userInfoGetReq,
  checkEmailReq,
  checkPasswordReq,
  likeGetReq,
  likeDeleteReq,
  likePostReq,
  likePhotoReq,
  withDrawReq,
} from "./user/";
import {
  placeActions,
  myPlaceListReq,
  placeDataReq,
  searchPlaceReq,
  recommendReq,
  searchSpotPostReq,
  searchSpotGetReq,
  planPostReq,
  planGetReq,
  planDeleteReq,
  planSearchReq,
} from "./place";
import { headerActions } from "./header";
export const Actions = {
  modalActions,
  userActions,
  placeActions,
  headerActions,
  signInReq,
  signUpReq,
  nonUserReq,
  googleReq,
  kakaoReq,
  userInfoPostReq,
  userInfoGetReq,
  checkEmailReq,
  checkPasswordReq,
  withDrawReq,
  likeGetReq,
  likeDeleteReq,
  likePostReq,
  likePhotoReq,
  myPlaceListReq,
  placeDataReq,
  searchPlaceReq,
  recommendReq,
  searchSpotPostReq,
  searchSpotGetReq,
  planPostReq,
  planGetReq,
  planDeleteReq,
  planSearchReq,
};
